---
kind: Service
apiVersion: v1
metadata:
  name: appservice
spec:
  selector:
    app: yalvapp
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
      nodePort: 30070
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: myappdeployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: yalvapp
    spec:
      containers:
        - name: yalvapp
          image: huyd/yalvservice
          ports: 
            - containerPort: 8000